safe:        false
port:        4000
baseurl:     ""
url:         http://bitcoinxt.website

source:      .
destination: ./_site
plugins_dir: ./_plugins
exclude:
    - Gemfile
    - Gemfile.lock
    - vendor
    - README.md


sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-multiple-languages-plugin

languages: ["en", "ru"]

exclude_from_localizations: [
    "css",
    "img",
    "favicon.ico",
    "favicon.png",
    "industry-letter.pdf",
    "robots.txt",
    "onboard.html"
    ]
